name: default

split: test
checkpoint_path: null

device: auto
top_k: 3

reports_dir: ${paths.reports_dir}/evaluation/${model.name}
plots_dir: ${paths.plots_dir}/${model.name}

log_to_mlflow: ${logging.enabled}
mlflow_run_name: evaluation-${model.name}
